### ISSUE TITLE
Errors at building

### ISSUE THREAD

**Issue by cvargascesp** [christianklotz/or-tools-lambda#3]
Hello. could you please help me to find out what i would be missing when running 

`$ docker build -t or-tools-lambda .`

<img width="754" alt="screen shot 2018-08-13 at 2 52 56 pm" src="https://user-images.githubusercontent.com/5656427/44052791-9c9c9272-9f0b-11e8-99aa-da3984e1e4e3.png">

Thanks in advance

**Comment by christianklotz** [comment]
Thank you for pointing out. Fixed in a86b4b4240168e53252dae6375b65a95f571177f.
